#!/usr/bin/env bash

# Elaina Theme Setter

# GTK
sed -i 's_Shirin_Elaina_' ~/{.gtkrc-2.0,.config/gtk-3.0/settings.ini}

# Icon
sed -i 's_Papirus-Custom_Papirus-Dark-Custom_' ~/{.gtkrc-2.0,.config/gtk-3.0/settings.ini,.config/qt5ct/qt5ct.conf}

# Openbox
sed -i 's_Shirin_Elaina_' ~/.config/openbox/rc.xml

# Rofi (didn't make rofi theme yet)
# sed -i 's_fullscreen-crimson_fullscreen-dark_' ~/.config/rofi/themes/shared/settings.rasi
# sed -i 's_sidebar-crimson_sidebar-dark_' ~/.config/rofi/themes/sidebar/colors.rasi

# Set Openbox Margin
sed -i 's_<top>30</top>_<top>10</top>_' ~/.config/openbox/rc.xml
sed -i 's_<bottom>10</bottom>_<bottom>40</bottom>_' ~/.config/openbox/rc.xml

# Xresources
cp ~/.resources/.Xresources-elaina ~/.Xresources
xrdb ~/.Xresources

# Reconfigure Openbox
openbox --reconfigure
