#!/usr/bin/env bash

# Mechanical Theme UI

# Background Handler
feh --bg-fill ~/.wallpaper/elaina-darken.png

# Panel
#tint2 -c ~/.config/tint2/elaina.tint2rc &
#tint2 -c ~/.config/tint2/elaina-2.tint2rc &
#tint2 -c ~/.config/tint2/elaina-3.tint2rc &
polybar -c ~/.config/polybar/Elaina/main.ini elaina &

# Notification Daemon
dunst -config ~/.config/dunst/dunstrc-nord &
