#!/usr/bin/env bash

# Start Aocchi Theme

current="$(cat ~/.config/openbox/visual-mode/current)"

if [[ $current != *"aocchi"* ]]; then

    # Kill Current
    bash -c '~/.config/openbox/visual-mode/kill-ui'
    
    # Set UI & Theme
    bash -c '~/.config/openbox/visual-mode/aocchi/theme'
    bash -c '~/.config/openbox/visual-mode/aocchi/ui'
    
    # Tray
    bash -c '~/.config/openbox/tray'
    
    # Write Current
    echo "aocchi" > ~/.config/openbox/visual-mode/current

    # Notify Success
    notify-send -u low -i lookswitcher "Visual Mode" "Aocchi Theme Applied"

else

    # Notify Fail
    notify-send -u low -i lookswitcher "Visual Mode" "You're Already in Aocchi Theme"
    
fi
