#!/usr/bin/env bash

# Start Shirin Theme

current="$(cat ~/.config/openbox/visual-mode/current)"

if [[ $current != *"elaina"* ]]; then

    # Kill Current
    bash -c '~/.config/openbox/visual-mode/kill-ui'
    
    # Set UI & Theme
    bash -c '~/.config/openbox/visual-mode/elaina/theme'
    bash -c '~/.config/openbox/visual-mode/elaina/ui'
    
    # Tray
    bash -c '~/.config/openbox/tray'
    
    # Write Current
    echo "elaina" > ~/.config/openbox/visual-mode/current

    # Notify Success
    notify-send -u low -i lookswitcher "Visual Mode" "Shirin Theme Applied"

else

    # Notify Fail
    notify-send -u low -i lookswitcher "Visual Mode" "You're Already in Shirin Theme"
    
fi
