#!/usr/bin/env bash

# Mechanical Theme UI

# Background Handler
feh --bg-fill ~/.wallpaper/communautique.png

# Panel
polybar -c ~/.config/polybar/Shirin/main.ini main &

# Notification Daemon
dunst -config ~/.config/dunst/dunstrc-dark &
