#!/usr/bin/env bash

# Mechanical Theme Setter

# GTK
sed -i 's_Fleon_Crimson_' ~/{.gtkrc-2.0,.config/gtk-3.0/settings.ini}

# Icon
sed -i 's_Papirus-Custom_Papirus-Dark-Custom_' ~/{.gtkrc-2.0,.config/gtk-3.0/settings.ini,.config/qt5ct/qt5ct.conf}

# Openbox
sed -i 's_Shirin_Aocchi_' ~/.config/openbox/rc.xml

# Rofi
sed -i 's_fullscreen-dark_fullscreen-crimson_' ~/.config/rofi/themes/shared/settings.rasi
sed -i 's_sidebar-dark_sidebar-crimson_' ~/.config/rofi/themes/sidebar/colors.rasi

# Set Openbox Margin
#sed -i 's_<top>10</top>_<top>30</top>_' ~/.config/openbox/rc.xml
sed -i 's_<bottom>10</bottom>_<bottom>30</bottom>_' ~/.config/openbox/rc.xml

# Reconfigure Openbox
openbox --reconfigure
